apiVersion: batch/v1
kind: CronJob
metadata:
  name: debug mongodb
spec:
  schedule: "*/1 * * * *"  # Cron expression for running every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debug_mongodb
            image: jorik2020/python_mongodb:2  # Replace with your actual image name and tag
            command: ["poetry", "run", "python", "mongodb_pandas_project/main.py", "test"]  # Command to run your script
          restartPolicy: OnFailure
