apiVersion: batch/v1
kind: CronJob
metadata:
  name: debug-mongodb
spec:
  schedule: "*/1 * * * *"  # Cron expression for running every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debug-mongodb
            image: jorik2020/python_mongodb:6  # Replace with your actual image name and tag
            command: ["poetry", "run", "python", "-m", "mongodb_pandas_project.main", "test"]  # Command to run your script
          restartPolicy: OnFailure