apiVersion: batch/v1
kind: CronJob
metadata:
  name: debug-mongodb
  namespace: wappe
spec:
  schedule: "*/10 * * * *"  # Cron expression for running every 5 minutes
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: debug-mongodb
            image: jorik2020/python_mongodb:6.1  # Replace with your actual image name and tag
            command: ["poetry", "run", "python", "-m", "mongodb_pandas_project.main", "start"]  # Command to run your script
            env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: wappe
                  key: MONGODB_URI
            - name: MONGODB_NAME
              valueFrom:
                secretKeyRef:
                  name: wappe
                  key: MONGODB_NAME
            - name: AZURE_CONN_STR
              valueFrom:
                secretKeyRef:
                  name: wappe
                  key: AZURE_CONN_STR
            - name: AZURE_CONTAINER
              valueFrom:
                secretKeyRef:
                  name: wappe
                  key: AZURE_CONTAINER
          restartPolicy: OnFailure